Pizza.NET/Models/Category.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure.Pluralization;
using System.Linq;
using System.Web;
using Humanizer;

namespace PizzaDotNet.Models
{
    public class Category : AbstractItem
    {
        public string Name { get; set; }
        public List<MenuItem> MenuItems { get; set; }
        public string NamePlural { get => Name.Pluralize(); }
        public string ImageName { get => Name?.Replace(" ", string.Empty); }
    }
}

Pizza.NET/Controllers/CartController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using PizzaDotNet.Models;

namespace PizzaDotNet.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
        private ApplicationDbContext context;
        private ApplicationUser user;

        public CartController()
        {
            context = new ApplicationDbContext();
        }

        // GET: Cart
        [HttpGet]
        public ActionResult Index()
        {
            return View(user.Cart);
        }

        // GET: Cart/ItemsNumber
        [HttpGet]
        public int ItemsNumber()
        {
            return user.Cart.ItemsNumber;
        }

        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            base.OnActionExecuting(filterContext);
            var userId = User.Identity.GetUserId();
            user = context.Users
                .Where(u => u.Id == userId)
                .Include(u => u.Cart.CartItems.Select(ci => ci.MenuItem))
                .Single();
        }
    }
}

Pizza.NET/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PizzaDotNet.Models;
using System.Data.Entity;
using Microsoft.AspNet.Identity;

namespace PizzaDotNet.Controllers
{
    public class HomeController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult Index()
        {
            return View(db.Categories.ToList());
        }

        // GET: Home/Category/5?select=2
        public ActionResult Category(int? id, int? select)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Include(cat => cat.MenuItems).First(cat => cat.Id == id);

            if (category == null)
            {
                return HttpNotFound();
            }

            ViewBag.SelectedId = select;
            return View(category);
        }

        public ActionResult About()
        {
            return View();
        }
    }
}

Pizza.NET/Controllers/OrderController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using PizzaDotNet.Models;

namespace PizzaDotNet.Controllers
{
    public class OrderController : Controller
    {
        private ApplicationDbContext context = new ApplicationDbContext();
        private ApplicationUser user;

        [HttpGet]
        public ActionResult Index()
        {
            var orders = context.Orders
                .Include(o => o.Address)
                .Include(o => o.Cart.CartItems.Select(ci => ci.MenuItem))
                .Where(o => o.User.Id == user.Id)
                .ToList();

            return View(orders);
        }

        // GET: Order/Checkout
        [HttpGet]
        public ActionResult Checkout()
        {
            if (user.Cart.CartItems.Count < 1)
                return RedirectToAction("Index", "Home");
            return View();
        }

        // POST: Order/Checkout
        [HttpPost]
        public async Task<ActionResult> Checkout(OrderViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var order = new Order
            {
                Address = model.Address,
                Name = $"{model.LastName}, {model.FirstName}",
                Telephone = model.Telephone,
                Cart = user.Cart,
                User = user
            };
            context.Entry(order).State = EntityState.Added;

            user.NewEmptyCart();
            context.Entry(user.Cart).State = EntityState.Added;

            await context.SaveChangesAsync();

            return RedirectToAction("Finished", new { id = order.Id });
        }

        // GET: Cart/Finished/2
        [HttpGet]
        public ActionResult Finished(int id)
        {
            var order = context.Orders
                .Include(o => o.User)
                .Include(o => o.Address)
                .Include(o => o.Cart.CartItems.Select(ci => ci.MenuItem))
                .First(o => o.Id == id);

            if (order == null || order.User.Id != User.Identity.GetUserId())
                return HttpNotFound();
            return View(order);
        }

        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            base.OnActionExecuting(filterContext);
            var userId = User.Identity.GetUserId();
            user = context.Users
                .Where(u => u.Id == userId)
                .Include(u => u.Cart.CartItems.Select(ci => ci.MenuItem))
                .Single();
        }
    }
}

Pizza.NET/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title</h2>

<p>The public repository can be found <a href="https://gitlab.com/Leblayd/Pizza.NET">here</a></p>

<address>
    <strong>Developed by</strong>
    <a href="mailto:leblaydavid7@gmail.com">Leblay Dávid</a><br />
</address>

Pizza.NET/Views/Home/Category.cshtml
@model PizzaDotNet.Models.Category

@{
    ViewBag.Title = "Details";
}

@section Left {
    <h2>@Html.Name(Model.NamePlural)</h2>
    <hr />

    <table class="table">
        <thead>
            <tr>
                <th>Name</th>
                <th>Description</th>
                <th class="text-center">Info</th>
                <th>Price</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var model in Model.MenuItems)
            {
                var modelId = @model.Id.ToString();
                // TODO replace the alert-info class with a custom, probably JS implementation
                <tr id="item-@modelId" class="@(ViewBag.SelectedId == model.Id ? "alert-info" : "")">
                    <td>@Html.Name(model.Name)</td>
                    <td>@Html.Name(model.Description)</td>
                    <td class="text-center">
                        @if (model.Vegetarian.GetValueOrDefault())
                        {
                            <span title="Vegetarian" class="food-info-icon noselect" style="color: green">&#129367;</span>
                        }
                        @if (model.Spicy.GetValueOrDefault())
                        {
                            <span title="Spicy" class="food-info-icon noselect" style="color: red">&#127798;</span>
                        }
                    </td>
                    <td>@Html.Name(model.Price.ToString())</td>
                    <td>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <div class="btn btn-success add-to-cart-button" style="cursor: pointer" data-id="@modelId">Buy</div>
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>
}

@section Right {
    <div class="text-center">
        <div class="category image-bg noselect" style="background-image: url(/Content/Images/@(Model.ImageName).jpg)">@Model.NamePlural</div>

        <hr />
        @if (!User.Identity.IsAuthenticated)
        {
            <strong>
                Please @Html.ActionLink("log in", "Login", "Account") or
                @Html.ActionLink("register", "Register", "Account") to be able to use the cart.
            </strong>
        }
        else if (int.Parse(Html.Action("ItemsNumber", "Cart").ToString()) > 0)
        {
            @Html.ActionLink("Checkout", "Checkout", "Order", null, new { @class = "btn btn-block btn-success" })
            @Html.ActionLink("Cart", "Index", "Cart", null, new { @class = "btn btn-block btn-primary" })
        }
        @Html.ActionLink("Go back", "Index", null, new { @class = "btn btn-warning btn-block" })
    </div>
}

@section scripts{
    <script>
        $(function () {
            $(".add-to-cart-button").on("click", function (e) {
                var request = $.ajax({
                    type: "POST",
                    url: `/api/Cart/${e.target.dataset["id"]}`
                });

                request.done(function (cart) {
                    Popup("alert-success", "Success!", "Item added to cart.");

                    UpdateCartItems(cart.ItemsNumber);
                });

                request.fail(ExceptionPopup);
            });
        })
    </script>
}

Pizza.NET/Views/Home/Index.cshtml
@model IEnumerable<PizzaDotNet.Models.Category>

@{
    ViewBag.Title = "Home Page";
}

@section Left{
    <div class="row text-center">
        <h1>Choose what you would like to eat</h1>
    </div>
    <div class="row text-center">
        @foreach (var item in Model)
        {
            <a class="row col-md-6 no-decoration category image-bg" style="background-image: url(/Content/Images/@(item.ImageName).jpg)"
               href="@Url.Action("Category", "Home", new { id = item.Id })">
                @item.NamePlural
            </a>
        }
    </div>
}

@section Right{
    <div class="text-center form-group">
        <label for="search" class="control-label" style="display: block">Search</label>
        <input id="search-input" name="search" class="form-control search-input"/>
        <a id="search-button" href="#" class="no-decoration btn search-icon">
            <i class="fas fa-search"></i>
        </a>
        <hr />
    </div>
    <div id="search-results"></div>
}

@section scripts{
    <script>
        function getSearchData() {
            let search = $("#search-input").val();
            let request = $.ajax({
                url: `/api/Items?search=${search}`
            });

            request.done((list) => fillWithData(list))
        }

        function fillWithData(list) {
            let results = $("#search-results");
            results.empty();
            if (list.menuItems[0]) {
                results.append(resultContainerHtml("Items"));
                for (let i in list.menuItems) {
                    let item = list.menuItems[i];
                    if (item.Category) { // temporary fix because Cézár saláta breaks everything
                        $("#search-results-Items").append(resultHtmlItem(item.Name, `/Home/Category/${item.Category.Id}?select=${item.Id}`));
                    }
                }
            }
            if (list.categories[0]) {
                results.append(resultContainerHtml("Categories"));
                for (let i in list.categories) {
                    let cat = list.categories[i];
                    $("#search-results-Categories").append(resultHtmlItem(cat.NamePlural, "/Home/Category/" + cat.Id));
                }
            }
        }

        function resultHtmlItem(name, link) {
            return `<div><a href=${link} class="animate-pop btn-lg">${name}</a></div>`;
        }

        function resultContainerHtml(name) {
            return `<div id="search-results-${name}" class="jumbotron" style="padding: 10px;"><h3>${name}</h3></div>`;
        }

        $(function () {
            $("#search-button").click(getSearchData);
            $("#search-input").keydown(event => {
                if (event.originalEvent.code === "Enter") getSearchData();
            });
        });
    </script>
}